version: '3' 

services: 
    fedAvg: 
        image: tjdghks994/fedpso
        network_mode: host
        volumes: 
        - .:/fl
        command: bash -c "sleep 1; python /fl/FedPSO/fed_avg.py"
    
    fedPSO:
        image: tjdghks994/fedpso
        network_mode: host
        volumes: 
        - .:/fl
        command: bash -c "sleep 1; python /fl/FedPSO/fed_pso.py"